source 'https://rubygems.org'

gem 'adhearsion'
gem 'punchblock', :git => 'git@github.com:adhearsion/punchblock.git', :branch => 'f939ecabed9f4922cf446cc22ff1d0e42c9632e5'
gem 'adhearsion-asr'
gem 'adhearsion-asterisk'
